version: '1.0'
stages:
  - checkout
  - package
  - upload
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: checkout
  BuildDockerImage:
    title: Building Docker image
    type: build
    stage: package
    image_name: dzirkler/openvpn-client
    working_directory: ./
    tag: v0.0.1
    dockerfile: Dockerfile
  PushLatest:
    title: Pushing latest image to Docker Hub
    stage: upload
    type: push
    arguments:
      candidate: '${{BuildDockerImage}}'
      tag: latest
      image_name: dzirkler/openvpn-client
      registry: dockerhub
      when:
        condition:
          all:
            masterBranch: '"${{CF_BRANCH}}" == "master"'
  PushBranch:
    title: Pushing tagged image to Docker Hub
    stage: upload
    type: push
    arguments:
      candidate: '${{BuildDockerImage}}'
      tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
      image_name: dzirkler/openvpn-client
      registry: dockerhub
